export const SKILLS = [
  // Software & Web Development
  "Web Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "React.js",
  "Vue.js",
  "Angular",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Next.js",
  "REST APIs",
  "GraphQL",
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "SQLite",
  "Firebase",
  "Docker",
  "CI/CD",
  "Git",
  "GitHub",
  "Testing (Jest, Mocha)",
  "TypeScript",
  "JavaScript",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "SASS",
  "WebSockets",
  "Web Performance Optimization",

  // Mobile Development
  "Mobile Development",
  "React Native",
  "Flutter",
  "Swift",
  "Kotlin",
  "Android Development",
  "iOS Development",

  // Data & AI
  "Data Analysis",
  "Data Visualization",
  "Python",
  "R",
  "Pandas",
  "NumPy",
  "Power BI",
  "Tableau",
  "Excel",
  "SQL",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "NLP",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Scikit-learn",
  "Data Engineering",

  // DevOps & Cloud
  "DevOps",
  "AWS",
  "Azure",
  "Google Cloud Platform (GCP)",
  "Terraform",
  "Kubernetes",
  "Ansible",
  "Jenkins",
  "Linux",

  // Cybersecurity
  "Cyber Security",
  "Network Security",
  "Penetration Testing",
  "Ethical Hacking",
  "Cryptography",
  "Security Auditing",

  // Product & Project
  "Project Management",
  "Product Management",
  "Agile",
  "Scrum",
  "Jira",
  "Confluence",
  "Notion",
  "Trello",

  // Business & Marketing
  "Digital Marketing",
  "Email Marketing",
  "SEO",
  "Search Engine Marketing (SEM)",
  "Social Media Marketing",
  "Content Marketing",
  "Google Ads",
  "Analytics",
  "Copywriting",
  "Market Research",
  "Salesforce",
  "CRM Management",

  // Design & Creative
  "Graphic Design",
  "UI/UX Design",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Figma",
  "Sketch",
  "Canva",
  "Prototyping",
  "Wireframing",
  "Branding",

  // Writing & Communication
  "Content Writing",
  "Technical Writing",
  "Blog Writing",
  "Copywriting",
  "Editing",
  "Proofreading",
  "Translation",
  "Public Speaking",
  "Presentation Skills",

  // Other General Skills
  "Critical Thinking",
  "Problem Solving",
  "Teamwork",
  "Time Management",
  "Adaptability",
  "Leadership",
  "Customer Service",
  "Negotiation",
  "Conflict Resolution",
  "Strategic Planning",
  "Research Skills",
  "Data Entry",
  "Typing",
];


export const STATUS_PRIORITY = {
  "Offer": 1,
  "Interview": 2,
  "Shortlisted": 3,
  "Viewed": 4,
  "Submitted": 5,
  "Pending": 6,
  "Rejected": 7
};
